CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name            TEXT,
  last_name             TEXT,
  address               TEXT,
  city                  TEXT,
  telephone             TEXT,
  email                 TEXT,
  notification_preference TEXT DEFAULT 'NONE'
);
CREATE INDEX ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON visits (pet_id);

CREATE TABLE IF NOT EXISTS notifications (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message        TEXT NOT NULL,
  type           TEXT NOT NULL,
  status         TEXT NOT NULL,
  scheduled_time TIMESTAMP NOT NULL,
  sent_time      TIMESTAMP,
  owner_id       INT NOT NULL REFERENCES owners (id),
  pet_id         INT REFERENCES pets (id)
);
CREATE INDEX ON notifications (owner_id);
CREATE INDEX ON notifications (pet_id);
CREATE INDEX ON notifications (status);

CREATE TABLE IF NOT EXISTS notification_schedules (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_template TEXT NOT NULL,
  type             TEXT NOT NULL,
  scheduled_time   TIMESTAMP NOT NULL,
  days_before      INT,
  enabled          BOOLEAN DEFAULT TRUE,
  owner_id         INT NOT NULL REFERENCES owners (id),
  pet_id           INT REFERENCES pets (id),
  visit_id         INT REFERENCES visits (id)
);
CREATE INDEX ON notification_schedules (owner_id);
CREATE INDEX ON notification_schedules (pet_id);
CREATE INDEX ON notification_schedules (visit_id);
